name       : gnome-shell-extensions
version    : 3.18.2
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-shell-extensions/3.18/gnome-shell-extensions-3.18.2.tar.xz : cc514ffc896ed8c04853a89cb8e97058f9d5518313becf7c92aea5210b8adf61
license    : GPL-2.0
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
builddeps  :
setup      : |
    %configure --enable-extensions=all
build      : |
    %make
install    : |
    %make_install
