name       : gnome-shell-extensions
version    : 3.36.3
release    : 26
source     :
    - https://download.gnome.org/sources/gnome-shell-extensions/3.36/gnome-shell-extensions-3.36.3.tar.xz : 2b674c4dc16f2ce46f07eea00a1754b243a19b469165a171cb1fbdbe376ee3b1
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
rundeps    :
    - libgnome-menus
setup      : |
    %meson_configure -Dextension_set='all'
build      : |
    %ninja_build
install    : |
    %ninja_install
