name       : gnome-shell-extensions
version    : 3.20.1
release    : 5
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-shell-extensions/3.20/gnome-shell-extensions-3.20.1.tar.xz : bc432ec163c79794331290d7a9321bee184be077d348faf3b7a1639b672939a3
license    : GPL-2.0
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
component  : desktop.gnome
setup      : |
    %configure --enable-extensions=all
build      : |
    %make
install    : |
    %make_install
