name       : gnome-shell-extensions
version    : 3.36.1
release    : 23
source     :
    - https://download.gnome.org/sources/gnome-shell-extensions/3.36/gnome-shell-extensions-3.36.1.tar.xz : de18927a7d0f5652628d97f03e102c84e576b9c873a878b8e1a53c21183b5039
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
rundeps    :
    - chrome-gnome-shell
    - libgnome-menus
setup      : |
    %meson_configure -Dextension_set='all'
build      : |
    %ninja_build
install    : |
    %ninja_install
