name       : gnome-shell-extensions
version    : 3.18.1
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-shell-extensions/3.18/gnome-shell-extensions-3.18.1.tar.xz : 7a7535420c0c808d28b5912ed42cfb221930010193083f2d8a7719ea1ffa1cc2
license    : GPL-2.0
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
builddeps  :
setup      : |
    %configure --enable-extensions=all
build      : |
    %make
install    : |
    %make_install
