name       : gnome-shell-extensions
version    : 3.38.1
release    : 27
source     :
    - https://download.gnome.org/sources/gnome-shell-extensions/3.38/gnome-shell-extensions-3.38.1.tar.xz : 9da38631ffb804284753e5d592f88b7953215cb8967d7a1c4f652d289f040c94
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
rundeps    :
    - libgnome-menus
setup      : |
    %meson_configure -Dextension_set='all'
build      : |
    %ninja_build
install    : |
    %ninja_install
