name       : gnome-shell-extensions
version    : '40.3'
release    : 32
source     :
    - https://download.gnome.org/sources/gnome-shell-extensions/40/gnome-shell-extensions-40.3.tar.xz : 9df87fa9535201febca3d508fdbf7bad0171cf7a27cb664dd4e3c1f96c4ed04b
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
builddeps  :
    - pkgconfig(gtk4)
rundeps    :
    - libgnome-menus
    - libgtk-4
setup      : |
    %meson_configure -Dextension_set='all'
build      : |
    %ninja_build
install    : |
    %ninja_install
