name       : gnome-shell-extensions
version    : '40.0'
release    : 29
source     :
    - https://download.gnome.org/sources/gnome-shell-extensions/40/gnome-shell-extensions-40.0.tar.xz : 172d85b2819ac9825c0ce91ed7324394d2e03b6569c4e8b60edd8a9e2f990a96
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
rundeps    :
    - libgnome-menus
builddeps  :
    - pkgconfig(gtk4)
rundeps    :
    - libgtk-4
setup      : |
    %meson_configure -Dextension_set='all'
build      : |
    %ninja_build
install    : |
    %ninja_install
