name       : gnome-shell-extensions
version    : 3.26.2
release    : 15
source     :
    - https://download.gnome.org/sources/gnome-shell-extensions/3.26/gnome-shell-extensions-3.26.2.tar.xz : aefda4d810ef5ceb9402e2d620f4bdc1dc40c9cc4f6a51749840f7dd08628ab6
license    : GPL-2.0
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
rundeps    :
    - chrome-gnome-shell
    - libgnome-menus
setup      : |
    %configure --enable-extensions=all
build      : |
    %make
install    : |
    %make_install
