name       : gnome-shell-extensions
version    : 3.36.0
release    : 22
source     :
    - https://download.gnome.org/sources/gnome-shell-extensions/3.36/gnome-shell-extensions-3.36.0.tar.xz : b5b29f974d05756130c785bf8e111c0ee43040161947f56bdd3a36871933b1e6
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
rundeps    :
    - chrome-gnome-shell
    - libgnome-menus
setup      : |
    %meson_configure -Dextension_set='all'
build      : |
    %ninja_build
install    : |
    %ninja_install
