name       : gnome-shell-extensions
version    : 3.28.1
release    : 17
source     :
    - git|https://gitlab.gnome.org/GNOME/gnome-shell-extensions.git : 3.28.1
license    : GPL-2.0
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
rundeps    :
    - chrome-gnome-shell
    - libgnome-menus
setup      : |
    %meson_configure -Dextension_set='all'
build      : |
    %ninja_build
install    : |
    %ninja_install
