name       : gnome-shell-extensions
version    : 3.36.2
release    : 24
source     :
    - https://download.gnome.org/sources/gnome-shell-extensions/3.36/gnome-shell-extensions-3.36.2.tar.xz : 978202de515cdb03a5885859c538366bca8fd78762ce98b172ac2c0126f8003f
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
rundeps    :
    - chrome-gnome-shell
    - libgnome-menus
setup      : |
    %meson_configure -Dextension_set='all'
build      : |
    %ninja_build
install    : |
    %ninja_install
