name       : gnome-shell-extensions
version    : 3.24.2
release    : 12
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-shell-extensions/3.24/gnome-shell-extensions-3.24.2.tar.xz : 9a1cc6c17dcf692121bdfe503d4e386a0992b2c976f90bd2f495155af9414f83
license    : GPL-2.0
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
rundeps    :
    - chrome-gnome-shell
    - libgnome-menus
setup      : |
    %configure --enable-extensions=all
build      : |
    %make
install    : |
    %make_install
