name       : gnome-shell-extensions
version    : '42.3'
release    : 37
source     :
    - https://download.gnome.org/sources/gnome-shell-extensions/42/gnome-shell-extensions-42.3.tar.xz : 0ec2bea32e9f28ac805891f613194d48fc0c091f09c48313065a3884f72273fc
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
builddeps  :
    - pkgconfig(gtk4)
rundeps    :
    - libgnome-menus
    - libgtk-4
setup      : |
    %meson_configure -Dextension_set='all'
build      : |
    %ninja_build
install    : |
    %ninja_install
