name       : gnome-shell-extensions
version    : 3.38.2
release    : 28
source     :
    - https://download.gnome.org/sources/gnome-shell-extensions/3.38/gnome-shell-extensions-3.38.2.tar.xz : 57a44279a750215af51ff29162b7b7a7b287f6afa0a28bb51d3b27b2cb49f643
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
rundeps    :
    - libgnome-menus
setup      : |
    %meson_configure -Dextension_set='all'
build      : |
    %ninja_build
install    : |
    %ninja_install
