name       : gnome-shell-extensions
version    : 3.24.0
release    : 8
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-shell-extensions/3.24/gnome-shell-extensions-3.24.0.tar.xz : a1f453cce7543a09f3d5515918a6fe903c1b4aa578f7367335dd1a8121d2618f
license    : GPL-2.0
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
rundeps    :
    - chrome-gnome-shell
setup      : |
    %configure --enable-extensions=all
build      : |
    %make
install    : |
    %make_install
