name       : gnome-shell-extensions
version    : 3.26.1
release    : 14
source     :
    - https://download.gnome.org/sources/gnome-shell-extensions/3.26/gnome-shell-extensions-3.26.1.tar.xz : 2437c6abce399a97ff95c2de9784580a5db82c59b67e09eaf2c8d972cca1d6d0
license    : GPL-2.0
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
rundeps    :
    - chrome-gnome-shell
    - libgnome-menus
setup      : |
    %configure --enable-extensions=all
build      : |
    %make
install    : |
    %make_install
