name       : gnome-shell-extensions
version    : 3.22.2
release    : 6
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-shell-extensions/3.22/gnome-shell-extensions-3.22.2.tar.xz : df7c22c69e29162bc1a7018b25b9a2fc37546451746b8b3c5109e5ac92238a87
license    : GPL-2.0
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
component  : desktop.gnome
setup      : |
    %configure --enable-extensions=all
build      : |
    %make
install    : |
    %make_install
