name       : gnome-shell-extensions
version    : 3.24.1
release    : 9
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-shell-extensions/3.24/gnome-shell-extensions-3.24.1.tar.xz : f8008064e732f1b29d8343c43b2b5ca029411af33e47b32a4daed2cae5b9aa60
license    : GPL-2.0
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
rundeps    :
    - chrome-gnome-shell
setup      : |
    %configure --enable-extensions=all
build      : |
    %make
install    : |
    %make_install
