name       : gnome-shell-extensions
version    : 3.34.0
release    : 19
source     :
    - https://download.gnome.org/sources/gnome-shell-extensions/3.34/gnome-shell-extensions-3.34.0.tar.xz : f5bf8f6a87f918ebba69adac56257b9439399238021821d689928e2b2822cbab
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
rundeps    :
    - chrome-gnome-shell
    - libgnome-menus
setup      : |
    %meson_configure -Dextension_set='all'
build      : |
    %ninja_build
install    : |
    %ninja_install
