name       : gnome-shell-extensions
version    : 3.18.3
release    : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-shell-extensions/3.18/gnome-shell-extensions-3.18.3.tar.xz : 2bb3726decf14a31ae35755c049d8f03425231857c42ed27f01854af755ec035
license    : GPL-2.0
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
setup      : |
    %configure --enable-extensions=all
build      : |
    %make
install    : |
    %make_install
