name       : gnome-shell-extensions
version    : 3.32.1
release    : 18
source     :
    - https://download.gnome.org/sources/gnome-shell-extensions/3.32/gnome-shell-extensions-3.32.1.tar.xz : 02b2b2fb477fcd8277ee3ce34ec156d97724011f2660dd2e14c412f18d5b911e
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : Extensions for GNOME Shell
description: |
    Extensions for GNOME Shell
rundeps    :
    - chrome-gnome-shell
    - libgnome-menus
setup      : |
    %meson_configure -Dextension_set='all'
build      : |
    %ninja_build
install    : |
    %ninja_install
